### PR TITLE
Fix the status property for our test server.

### PR DESCRIPTION
**Pull request by amateescu**

### CODE REVIEW

**Comment by Berdir** [comment]
Strange, wondering we we enable search_api_db in our test? :) That seems to be the one that is failing now.

**Comment by Berdir** [comment]
Or the db test module, actually.

**Comment by amateescu** [comment]
> wondering we we enable search_api_db in our test?

Because I never got to separate the test classes properly and \Drupal\search_api_solr\Tests\SearchApiSolrTest still extends \Drupal\search_api_db\Tests\BackendTest :P

**Comment by amateescu** [comment]
Opened an issue in search_api for that: https://www.drupal.org/node/2483179

**Pull request merged**
