### PR TITLE
Add installation steps to README file

### PR DESCRIPTION
**Pull request by anavarre**
It's easy to overlook the composer update. Let's clarify that and also add the basics to install the module

### CODE REVIEW

**Comment by Berdir** [comment]
Looks good, there's also an INSTALL.txt, that currently only covers installing Solr, maybe put it there instead?

I guess a hook_requirements() that prevents installation would also be a good idea, but that's a separate issue.

**Comment by anavarre** [comment]
So, I did notice **INSTALL.TXT** but it seemed to only focus on Apache Solr itself and I was under the impression that it would get the Drupal-related installation steps a bit buried there.

Since the **README.txt**  file is the one that is listed on Github and since it's a) the first thing you usually read and b) something that [we might end up implementing on d.o.](https://www.drupal.org/node/1674976) I assumed it would hit two birds with one stone.

Happy to submit another PR with the instructions added to **INSTALL.TXT** if you still believe it makes more sense.

**Comment by Berdir** [comment]
Consider me convinced ;)

**Comment by amateescu** [comment]
Me too!

**Pull request merged**
