### PR TITLE
getDataTypeInfo method was renamed to getDefaultDataTypes

### PR DESCRIPTION
**Pull request by ludohartzema**

### CODE REVIEW

**Comment by Berdir** [comment]
There's already a PR here: https://github.com/amateescu/search_api_solr/pull/59

**Comment by ludohartzema** [comment]
Sorry, I missed that one.

**Comment by Berdir** [comment]
I've merged the other one, I think we can close this one. We can discuss to rename the method, if you want to do that, feel free to rebase or open a new PR.. and if not, close it :) (You closed and re-opened, not sure why)

**Comment by ludohartzema** [comment]
I will close this one. Thanks for the feedback and the merge.
The first time closing it was done by clicking accidentally. :)

**Pull request closed without merging**
